### ISSUE TITLE
-fc89 and uint128

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/kremlin#105]
`-h` says:

```
The [-fc89] option triggers [-fnoanonymous-unions], [-fnocompound-literals] and
[-fc89-scope]. It also changes the invocations above to use [-std=c89]. Note
that if you're using the uint128 type, you will have to manually compile this
code with -DKRML_VERIFIED_UINT128.
```

Does this mean that `-fc89` will always use the slow UInt128s? (I need it to work with both.)

**Comment by msprotz** [comment]
The __uint128 (GCC) and __m128i (MSVC) types are not C89, so if you're *truly* targeting a C89 environment, you should use the slow uint128, as it is the only implementation that does not rely on non-standard vendor extensions. This is what the comment is meant to indicate.

However, from what I understand, you want to generate code that abides by *some* C89 restrictions, but that uses non-C89 vendor extensions in other places. Things will probably become clearer if you look at this header: https://github.com/FStarLang/kremlin/blob/master/include/kremlin/internal/types.h#L44 -- this is what controls which implementation of uint128 is used. In your case, you could choose to ignore the comment, and compile both your client code and kremlib (with a matching uint128 implementation) without KRML_VERIFIED_UINT128, but then it is up to you to ensure that the toochain you use supports __uint128 or __m128i.

Hope this helps,

**Comment by wintersteiger** [comment]
That's pretty much what I assumed, but I get a bunch of undefined references when I try to compile without `-DKRML_VERIFIED_UINT128`:

```
Hacl_Curve25519.c:(.text+0x356b): undefined reference to `FStar_UInt128_...`
```

My client code in this case is HACL code, which contains `extern` declarations and  calls to those functions (with and without `-fc89`). Does this indicate a problem on my end or is this expected?

**Comment by wintersteiger** [comment]
Aha! Found them. I hadn't seen kremlib/c/*c. yet.
