### ISSUE TITLE
Crash on if-then-else inside push/pop_frame

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/kremlin#12]
The following snippet

```F#
module Test

open FStar.HST
open FStar.Buffer
open FStar.UInt32
open FStar.Ghost

let test (b:buffer t) (x:t) (y:t) : Stack unit
  (requires (fun h -> True))
  (ensures  (fun h0 _ h1 -> True))
  =
    push_frame();
    let z =
      if (x <=^ y) then (
        let len =
          if (x =^ y) then 1ul else 2ul in
        if (x >=^ y) then b.(1ul) <- b.(0ul);
        0ul
      ) else (
        1ul
      ) in
    pop_frame();
    ()
```
passes F* extraction but Kremlin returns  `Fatal error: exception Failure("[AstToCStar.translate_expr EIfThenElse]: should not be here in declaration Test_test")`.

**Comment by msprotz** [comment]
I think I just fixed that problem in my `data_types` branch... let me know how it works for you

**Comment by msprotz** [comment]
I can confirm that the assertion is no longer thrown. Thanks for the testcase!
