### ISSUE TITLE
libc dependencies

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/kremlin#120]
kremlib contains calls to libc functions, e.g. `strcat` (https://github.com/FStarLang/kremlin/blob/master/kremlib/c/fstar_string.c#L19)

I find that a little annoying, because I'm working with a libc that doesn't come with it (very restricted library inside an SGX enclave via OpenEnclave). But, more to the point, I don't think we can trust random system libraries to respect any of our verification assumptions/guarantees. For the particular case of `strcat` it should be easy to provide an F* version that extracts to something reasonably efficient (happy to give it a go if this is wanted).

(Also, I can't use `exit`, but that was protected by a macro, so easier to work around.)

**Comment by wintersteiger** [comment]
I'm using whatever the Makefiles produce, currently mainly for the Merkle trees (which include parts of EverCrypt; set up by myself; probably not minimal) and I'm trying to start using EverCrypt directly, so I need whatever that needs. I don't think I had any direct references to `fstar_string.c`, but I'm mainly working in debug mode, so I guess it keeps whatever's there.

**Comment by msprotz** [comment]
After my merge from a few weeks ago, the Merkle tree library links against a "minimal" kremlib that no longer contains these symbols.
