### ISSUE TITLE
Review TODO

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/kremlin#122]
https://github.com/FStarLang/kremlin/blob/c61eec1d377bf6bd6b95980c122a266e8ae5dc90/include/kremlin/internal/callconv.h#L27

Would be nice if we could get that fixed/removed for https://github.com/ARMmbed/mbedtls/pull/2073#discussion_r241502664

**Comment by msprotz** [comment]
> If you are writing a header file to be included in ISO C90 programs, write __inline__ instead of inline. See Alternate Keywords.

(https://gcc.gnu.org/onlinedocs/gcc/Inline.html)

**Comment by wintersteiger** [comment]
That would be great, thanks! It's more of a note than an actual TODO.

**Comment by msprotz** [comment]
Fixed in 062c33e07d395b6d705906cae2f02bf75360faf7
