### ISSUE TITLE
Missing prototypes

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/kremlin#123]
Our integration with mbedTLS throws some missing prototypes warnings (https://github.com/ARMmbed/mbedtls/pull/2073#discussion_r241519651) for some functions in `fstar_uint128.c`:

```
../3rdparty/everest/library/kremlib/fstar_uint128.c:26:11: warning: no previous prototype for ‘load128_le’ [-Wmissing-prototypes]
 uint128_t load128_le(uint8_t *b) {
           ^~~~~~~~~~
../3rdparty/everest/library/kremlib/fstar_uint128.c:32:6: warning: no previous prototype for ‘store128_le’ [-Wmissing-prototypes]
 void store128_le(uint8_t *b, uint128_t n) {
      ^~~~~~~~~~~
../3rdparty/everest/library/kremlib/fstar_uint128.c:37:11: warning: no previous prototype for ‘load128_be’ [-Wmissing-prototypes]
 uint128_t load128_be(uint8_t *b) {
           ^~~~~~~~~~
../3rdparty/everest/library/kremlib/fstar_uint128.c:43:6: warning: no previous prototype for ‘store128_be’ [-Wmissing-prototypes]
 void store128_be(uint8_t *b, uint128_t n) {
      ^~~~~~~~~~~
../3rdparty/everest/library/kremlib/fstar_uint128.c:52:11: warning: no previous prototype for ‘FStar_UInt128_mul’ [-Wmissing-prototypes]
 uint128_t FStar_UInt128_mul(uint128_t x, uint128_t y) {
           ^~~~~~~~~~~~~~~~~
```

Should those have prototypes in `FStar_UInt128.h` or do I really need to include "kremlib/extracted/C_Endianness.h" and all that comes with it?

**Comment by wintersteiger** [comment]
(I'm not using the latest kremlib for this - would take too much code review time to update; please close if fixed and I'll find a different solution.)

**Comment by wintersteiger** [comment]
Actually, I think I can live without `fstar_uint128.c` for now as it seems to be built into my Hacl* extracts anyways.

**Comment by msprotz** [comment]
The dist/minimal flavor of kremlib is designed to fix this. Previously, C_Endianness would drag in a *ton* of dependencies. Now, in that directory (which I can zip up for you), C_Endianness is self-contained and you only need 3 C files and 3 H files.

Hope this helps,

Jonathan
