### ISSUE TITLE
'Getting Started' user documentation + sample Makefile

### ISSUE THREAD

**Issue by ghost** [FStarLang/kremlin#127]
The current Low* tutorial needs some work to help get a new developer started on their first project.

The [first chapter in Rust's book](https://doc.rust-lang.org/book/ch01-00-getting-started.html) might serve as inspiration, as it describes both the basic "Hello, World!" with rustc and "Hello, Cargo!" with the cargo build system.

Specifically, there is an outstanding TODO in the [Introduction](https://fstarlang.github.io/lowstar/html/Introduction.html):

> Section ?? provides a complete sample Makefile that performs parallel verification and extraction, along with parallel compilation of the resulting C code, using F*’s automated dependency analysis and `gcc -MM` for correct, incremental builds.

I'm happy to help test the documentation and provide input where I can. Thanks!

**Comment by msprotz** [comment]
Sorry it took me so long to get to this, but there's a brand new documentation with a sample project, under CI, and heavily commented things including build, how to structure your project, etc.. If you have time to give it a go, it'd be most grateful for pull requests and amendments to the documentation.

Thanks,

Jonathan
