### ISSUE TITLE
Tests fail due to options conflict using hardened GCC 8.3.0

### ISSUE THREAD

**Issue by ghost** [FStarLang/kremlin#131]
`make test` output from the latest master:

```
⚙ KreMLin will drive the C compiler. Here's what we found:                                                                                                 
gcc is: gcc                                                                                                                                                
gcc options are: -I /home/james/Code/kremlin/kremlib -I /home/james/Code/kremlin/include -I .output/TestKremBytes.out -Wall -Werror -Wno-unused-variable -Wn
o-unknown-warning-option -Wno-unused-but-set-variable -g -fwrapv -fstack-check -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wno-parentheses -std=c11                   
⚡ Generating object files                                                                                                                                  
✘ [CC,.output/TestKremBytes.out/TestKremBytes.c] (use -verbose to see the output)
cc1: error: ‘-fstack-check=’ and ‘-fstack-clash_protection’ are mutually exclusive.  Disabling ‘-fstack-check=’ [-Werror]                                  
cc1: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]                                                                       
cc1: all warnings being treated as errors 
```

After removing `-fstack-check` from `src/Options.ml` and building krml again, the tests pass.

I assume that `-fstack-clash-protection` is enabled because I am using a hardened toolchain with stack smashing protection (SSP) enabled.

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/8.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-8.3.0/work/gcc-8.3.0/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/8.3.0 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.3.0
--mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.3.0/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/8.3.0/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/8.3.0/python --enable-languages=c,c++,go,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo Hardened 8.3.0 p1.0' --enable-esp --enable-libstdcxx-time --disable-libstdcxx-pch --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-altivec --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libmudflap --disable-libssp --enable-libmpx --enable-systemtap --enable-vtable-verify --enable-lto --without-isl --enable-default-pie --enable-default-ssp
Thread model: posix

$ gcc --version
gcc (Gentoo Hardened 8.3.0 p1.0) 8.3.0
```

**Comment by msprotz** [comment]
Thanks. Using kremlin as a driver for the C compiler is becoming less and less supported, and this is one more reason to deprecate it.

**Comment by uranther** [comment]
@msprotz Another problem I had is with linking `libkremlib.a`. I ended up patching Makefile.basic in the KreMLin repository so it will use $(USER_CFLAGS) to include the necessary linking options to GCC. It's not exactly a foolproof solution, but it works for me for now.

**Comment by msprotz** [comment]
Is USER_CFLAGS a standard Unix variable or is it just a common Gentoo thing?

**Comment by uranther** [comment]
It's a variable in Makefile.include generated by KreMLin when passing in -ccopts.

-------- Original Message --------

**Comment by uranther** [comment]
@msprotz FWIW, Nim is another language the compiles to C and uses its own driver. There may be some ideas there for handling it in KreMLin.

- [Nim Compiler User Guide](https://nim-lang.org/docs/nimc.html)
- [Nim Backend Integration](https://nim-lang.org/docs/backends.html)
- [`extccomp.nim`](https://github.com/nim-lang/Nim/blob/master/compiler/extccomp.nim)

**Comment by msprotz** [comment]
Can you submit a pull request that removes -fstack-check? Also: you said you had to patch Makefile.basic; did this not work? https://github.com/FStarLang/kremlin/blob/master/misc/Makefile.basic#L24

**Comment by msprotz** [comment]
Thanks for the pointers to nim. But kremlin as a driver only works for the most minimal test cases -- for any reasonable project, I prefer to rely on the generated Makefile to get massive parallelism for the C compiler invocations.

**Comment by uranther** [comment]
Sure - I'll send some PRs shortly.

That line 24 doesn't help because the final compiler invocation only grabs the object files and spits them out to an executable (`cc 1.o 2.o 3.o -o all`). You'll see in the diff.

**Comment by uranther** [comment]
@msprotz Another source of inspiration is Zig. It actually ships with different libc's and has a more user-friendly `cc` frontend; it also has a build system with artifact caching. See the release notes: https://ziglang.org/download/0.4.0/release-notes.html

I would be interested in working on a language-native build system as a GSoC 2020 project. For one thing, I believe Make belongs in the 70s whence it came. And I want to support any developer productivity features that I've grown accustomed to in other modern languages.

Thanks for your consideration. Feel free to email me!

**Comment by picobyte** [comment]
There appear to be some overzealous clashing defaults that prevent building of yay:
`cc1: error: '-fstack-check=' and '-fstack-clash_protection' are mutually exclusive; disabling '-fstack-check=' [-Werror]
cc1: all warnings being treated as errors`
