### ISSUE TITLE
Migrate from ulex to sedlex

### ISSUE THREAD

**Issue by XVilka** [FStarLang/kremlin#138]
Long story short - ulex is dying, mainstream depends on the camlp4, which is dead, fork depends on the camlp5, which seems dead too. This prevents from porting to more modern OCaml versions and dependencies versions.

See these links for more information:
- https://discuss.ocaml.org/t/camlp5-and-ocaml-4-08/3985/4
- https://github.com/ocaml/opam-repository/pull/14351

Sedlex is an active maintained project by OCaml community: https://github.com/ocaml-community/sedlex

**Comment by msprotz** [comment]
Hello,

Yes, eventually I'd like to move. Is there any chance you could submit a pull request?

Thanks,

Jonathan

**Comment by s-zanella** [comment]
Updated PR in #144

**Comment by XVilka** [comment]
Perfect! Thank you.
