### ISSUE TITLE
Explicitly specify calling convention for function declarations

### ISSUE THREAD

**Issue by BarryBo** [FStarLang/kremlin#14]
The current extracted C code specifies no specific calling convention, so it gets the convention from the C compiler.  For the externs that are calls into Spartan code, we need to pin down a single convention - __stdcall.  Unfortunately, we need some of our code to be compiled with __cdecl as the default convention, and some with __stdcall as the default, and mixing between the two requires explicit conventions.

One option is to place an empty KREMLINCALL macro where the calling convention would be specified, and allow apps to override it with a specific convention.  Like this:
```
#ifndef KREMLINCALL
#define KREMLINCALL
#endif

extern int KREMLINCALL MyFunction(int arg1, char* arg2);

```
That way,  we could override KREMLINCALL ahead of including this code, to be __stdcall or __cdecl as we see fit.

**Comment by msprotz** [comment]
That sure seems like an easy solution; will you need to mix calling conventions? If you will, then I'm happy to extend the AST to allow you to specify an optional calling convention in a `DExternal` node.

**Comment by BarryBo** [comment]
Yes, I think we'll end up needing mixed conventions within a single .c file.  The extended attribute will need to be on DExternal and DFunction, so we can specify the conventions for both.

**Comment by msprotz** [comment]
Ok will add a new option then.

**Comment by msprotz** [comment]
Let me know how this works out for you -- I haven't tested it since this isn't something I surface at the F* level.

**Comment by BarryBo** [comment]
Close!

nhe ordering is incorrect in the generated code.  Today Kremlin generates the following, which does not compile:

__stdcall extern AESModule_Quadword *AESModule_aes_s_ShiftRows(AESModule_Quadword *x0);

needs to be

extern AESModule_Quadword * __stdcall AESModule_aes_s_ShiftRows(AESModule_Quadword *x0);

as the __stdcall modifies the function, not the visibility or return type.

Barry

**Comment by msprotz** [comment]
ha! ok, thanks will look into it

**Comment by msprotz** [comment]
Can you try out 5135e45 and let me know if it prints everything properly?

**Comment by BarryBo** [comment]
Confirmed - it works.
