### ISSUE TITLE
Generate const keyword

### ISSUE THREAD

**Issue by letmaik** [FStarLang/kremlin#147]
This continues https://github.com/FStarLang/kremlin/issues/53.

It would be really nice to have `const` in generated function arguments to avoid `const_cast`s in C++ user code.

**Comment by wintersteiger** [comment]
+1, I think we really should invest in that now that many Everest components are used independently, outside of miTLS.

**Comment by msprotz** [comment]
Thanks, const support now has landed. In order to take a const pointer over a variable, you can use the new `LowStar.ConstBuffer` in F*'s ulib. It will take a while before projects and libraries switch to  it but support is there!

Cheers,

Jonathan

**Comment by wintersteiger** [comment]
Is this just for buffers at this time? I need a `const merkle_tree`; does this mean I would have to duplicate the entire type hierarchy for const and non-const trees?

**Comment by ad-l** [comment]
ConstBuffer is only for pointer types (arrays and pointer)
