### ISSUE TITLE
gcmalloc generates code into kremlinit_globals

### ISSUE THREAD

**Issue by andricicezar** [FStarLang/kremlin#148]
Following a discussion on the slack channel #kremlin [here](https://everestexpedition.slack.com/archives/C1KM77U67/p1569323782014200?thread_ts=1569003096.006700&cid=C1KM77U67), @protz said this may be a bug

Kremlin version: Latest commit c04d180
F* version: F* 0.9.7.0-alpha1

The following F* code:
```fstar
module Test 

#set-options "--use_two_phase_tc true"

open FStar.HyperStack.ST

module S = FStar.Seq
module B = LowStar.Buffer
module M = LowStar.Modifies
module U32 = FStar.UInt32
module HS = FStar.HyperStack
module ST = FStar.HyperStack.ST

open LowStar.BufferOps

let n = 11ul

let arr: b:B.buffer U32.t=
  B.gcmalloc #U32.t HS.root 0ul n

let main (): Stack C.exit_code
  (requires fun _ -> True)
  (ensures fun h _ h' -> M.modifies M.loc_none h h')
=
  push_frame ();
  pop_frame ();
  C.EXIT_SUCCESS
```

generates the following C code:
```c
#include "Test.h"

uint32_t n = (uint32_t)11U;

uint32_t *arr;

exit_code main()
{
  kremlinit_globals();
  return EXIT_SUCCESS;
}
```

kremlinit.c
```c
#include "kremlinit.h"

#if defined(__GNUC__) && !(defined(_WIN32) || defined(_WIN64))
__attribute__ ((visibility ("hidden")))
#endif

void kremlinit_globals()
{
  KRML_CHECK_SIZE(sizeof (uint32_t), n);
  uint32_t *buf = KRML_HOST_CALLOC(n, sizeof (uint32_t));
  arr = buf;
}
```

**Comment by msprotz** [comment]
Can you try marking n inline for extraction?



~ jonathan

________________________________

**Comment by andricicezar** [comment]
Like this?

```
inline_for_extraction
let n = 11ul
```

There is no change in the extracted code. I tried also with inline for extraction for the array, and it there is no change either.

```
inline_for_extraction
let arr: b:B.buffer U32.t=
  B.gcmalloc #U32.t HS.root 0ul n
```

**Comment by msprotz** [comment]
Only `n` should be inline_for_extraction -- I thought it would help. Thanks for trying -- definitely looks like a bug.

In the meanwhile, you can try copying the pattern used elsewhere and pass in a list of 11 elements to gcmalloc_of_list (with suitable @inline_let attributes). Hit me up on Slack if you need an example of that added to the testsuite.

**Comment by s-zanella** [comment]
Both top-level buffers created with `LowStar.Buffer.gcmalloc` and uninitialized buffers created using `LowStar.UninitializedBuffer` extract as pointers with initialization code in `kremlinit_globals`. 

As long as their size is statically known, they can both be extracted as global arrays initialized implicitly. This is safe for uninitialized buffers and for 0-initialized buffers of integers like `gcmalloc 0ul 11ul` (see https://port70.net/~nsz/c/c89/c89-draft.html#3.5.7).

I opened a PR to do this: https://github.com/FStarLang/kremlin/pull/149, but need @msprotz  to check I did not screw up.

**Comment by msprotz** [comment]
Thanks Santiago, I could not find any issues with your patch so I've merged.

@andricicezar you should be good now -- but you still need to keep the `inline_for_extraction` on the `n`: kremlin needs to see a constant in the call to `gcmalloc`, so you need to rely on F* to inline that constant
