### ISSUE TITLE
If an output file is dropped due to a problem, any existing file should be deleted, or kremlin should return a failure code

### ISSUE THREAD

**Issue by BarryBo** [FStarLang/kremlin#15]
```
Dafny program verifier finished with 0 verified, 0 errors
Compiled program written to sha256_main.i.json
        ..\..\..\\tools\Kremlin\Kremlin.native sha256_main.i.json -warn-error +1..4 -skip-compilation -add-include \"DafnyLib.h\"
Warning 4: in declaration sha256_main_i.SHA256_DigestOneBlock, in the definition of sha256_main_i: Malformed input:
type mismatch, uint64_t (a.k.a. uint64_t) vs Dafny_BigInt (a.k.a. Dafny_BigInt)
Dropping sha256_main_i (at checking time)
KreMLin: writing out .c and .h files for words_and_bytes_i, Collections__Seqs_i, sha256_i, sha256_s, hmac_common_s, sha_common_s, words_and_bytes_s, assembly_s, Collections__Seqs_s, Math__power2_i, Math__div_i, Math__div_auto_i, Math__div_auto_proofs_i, Math__div_boogie_i, Math__div_def_i, Math__power_i, Math__power_s, Math__power2_s, Math__mod_auto_i, Math__mod_auto_proofs_i, Math__div_nonlin
```

This happened during our build, and we ended up with an out-of-date sha256_main_i.c/.h that then compiled but failed to link. 

I think Kremlin should delete files if it decides not to generate code.  Or warnings about dropped files should cause it to return non-zero, so that "make" will detect the failure and stop.

**Comment by BarryBo** [comment]
Acutally, I prefer both be done.

**Comment by msprotz** [comment]
Running with `-warn-error @4` would solve half of the problem... I guess?

**Comment by BarryBo** [comment]
Yes, that caused the build to halt.  I'll make that change in our makefile and check it in.

**Comment by msprotz** [comment]
I don't understand the second part of the issue. Kremlin generates code for all the files that it successfully checked, and then tentatively compiles & links them. If you make warning 4 fatal, then if any file fails to "type-check", then no file is written at all.

What is the behavior that you would like?

**Comment by BarryBo** [comment]
I'm asking for fail-safe, where if a file cannot be generated, an older version of the file doesn't get left behind, in case it is accidentally picked up by the downstream build process.

For now, I have done this in the makefile, by deleting the expected .c and .h files ahead of calling Kremlin.

**Comment by msprotz** [comment]
Ok. This is due to the philosophy of Kremlin-as-a-driver: since Kremlin usually drives the C compiler, it knows which set of files to pass it, and then returns a non-zero error code if the final linking phase failed.

I can offer two solutions:
- a warning (off by default, that you could make fatal) if the `-tmpdir` (the directory where kremlin writes all the files) is non-empty;
- have kremlin drive the MSVC compiler.

The latter would probably be better (there's also "gcc", "g++", "clang" and "compcert"); if you tell me how to figure out where the most recent version of MSVC lives, and which options I should pass to the compiler, I'm happy to make kremlin a driver for cl too.

**Comment by BarryBo** [comment]
I think Kremlin should not be driving the C compiler... the goal should be to produce standalone C code that is compilable via an existing product's build process.  For Spartan, I doubt we'll use the same compiler flags across all of the code we compile...we'll change optimization flags, calling conventions, debug symbols, include paths, etc.

The current Kremlin is workable as-is:  it reports a failure code if it fails to generate a .c file.  Our makefile pre-deletes any .c files before calling Kremlin, so we can be sure we have failed safely.

**Comment by msprotz** [comment]
Ok. I should make clear that we do want to generate usable C code; it's just that for development purposes, we've found it easier to let kremlin drive the compiler. This makes for a very concise Makefile https://github.com/FStarLang/kremlin/blob/master/test/Makefile

Anyhow, I'm happy to implement a warning if the output directory is not empty (and -skip-compilation is used).

**Comment by BarryBo** [comment]
We already have Kremlin in our main-line build process, and I use that to verify everything still works after making a Kremlin or Dafny change.

I don't think checking for empty will help... the case we are worried about is just one or more output going missing.

At this point, I'm OK closing out this issue... our build is robust against the kinds of errors we seem to make.
