### ISSUE TITLE
CAbstractStruct attribute is not propagated to implementations

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/kremlin#153]
Adding `[@CAbstractStruct]` to the declaration of a type in an interface has no effect. Adding the attribute to the definition works as intended, so it looks like the attribute isn't properly propagated.
Example:
- `A.fsti`
```FStar
[@CAbstractStruct]
val t : Type0
```
- `A.fst`
```FStar
type t =
| A: int -> t
| B: bool -> t
```
BTW, the test for this in `tests/AbstractStruct.fst` doesn't actually exercise this because it uses a record with a single field that gets extracted to a scalar rather than a struct.

**Comment by msprotz** [comment]
Thanks -- I thought there was something about attributes not being propagated between and fsti and fst that either @nikswamy or @mtzguido looked into. Does that ring a bell?

**Comment by s-zanella** [comment]
Yes, I believe we had a similar problem with `strict_on_arguments`. I don't know if it was ever resolved.

**Comment by mtzguido** [comment]
It rings a bell, see https://github.com/FStarLang/FStar/issues/1862, this seems like a variation of that.

**Comment by mtzguido** [comment]
This should be fixed now in F* master, could you confirm? (the fix is commit https://github.com/FStarLang/FStar/commit/783fd3e632f917173f4fe6d1ba038db563693fc1)

**Comment by s-zanella** [comment]
It didn't work when I tried on the KreMLin test in `test/AbstractStruct.fst`:
- `AbstractStruct.fsti`
```FStar
module AbstractStruct

[@CAbstractStruct]
val t : Type0

val main: unit -> St Int32.t
```
- `AbstractStruct.fst`
```FStar
module AbstractStruct

open FStar.HyperStack.ST

//[@CAbstractStruct]
type t = {
  x: Int32.t;
  b: bool;
}

let main () =
  let x: t = { x = 0l; b = true; } in
  x.x
```
Could it be because it's a `type` and not a `let`?

**Comment by s-zanella** [comment]
I think this change will have implications for existing code if attributes in interfaces that weren't propagated to implementations now will be. It would be wise to try a full Everest build.

**Comment by msprotz** [comment]
correct -- you'll most likely have to remove some CAbstractStruct declarations in EverCrypt until the problem is fixed in kremlin (abstractions are traversed in F* thanks for StackInline on the `alloca`-like functions that create abstract state on the caller's stack); however, in C, if CAbstractStruct kicks in, then the caller will *not* know the definition of the struct and this will result in a C compilation error

**Comment by mtzguido** [comment]
Indeed this was not working for actual inductive types, and only for abbreviations. I have a proper fix now, but will check with everest before merging. Thanks guys.

**Comment by mtzguido** [comment]
Now fixed in F* master, with an everest green after commenting out a single `CAbstractStruct` attribute: https://github.com/project-everest/hacl-star/commit/8f1d47e4b515c4390beb84c4d065dfc208556b5a.

**Comment by s-zanella** [comment]
The example I tried before works now. Thanks!
