### ISSUE TITLE
freebug?

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/kremlin#161]
https://github.com/FStarLang/kremlin/blob/fe104c22321a312128ae1db4ea142ad5bbba6b7b/src/PrintAst.ml#L235

I see the string `freebug` in my debug output... does this indicate that there's likely a bug somewhere or is that just a typo and it should be `freebuf`?

**Comment by msprotz** [comment]
should be freebuf :)

where are you seeing this?

**Comment by wintersteiger** [comment]
I'm debugging Merkle tree extraction (with parametrized hash sizes and partial functions, etc) and I get that in the output of `-dast`.
