### ISSUE TITLE
unfold vs inline_for_extraction

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/kremlin#162]
I've been tearing my hair out over kremlin not wanting to inline my functions marked with `inline_for_extraction`. I just tried marking them `unfold` instead and I promptly got a very helpful error message:

```
LowStar.RVector.fst(708,0-734,49): (Error 162) The qualifier list "[unfold]" is not permissible for this element: recursive definitions cannot be marked inline
```

I suppose the same is true for `inline_for_extraction`, but it just doesn't produce a warning/error and continues without inlining?

**Comment by msprotz** [comment]
thanks for the bug report and sorry to hear you had a frustrating experience

F* is responsible for unfolding things marked as `inline_for_extraction` so I would suggest filing this bug in FStarLang/FStar

there's a discussion on Slack on how to force unrolling of recursive functions: https://everestexpedition.slack.com/archives/C0N8CV6NA/p1571127278005900 you might find that it helps for your purposes

Thanks,

Jonathan

**Comment by wintersteiger** [comment]
Great, thanks for the pointers!
