### ISSUE TITLE
Doesn't build on ppc64le

### ISSUE THREAD

**Issue by clbr** [FStarLang/kremlin#166]
NSS now includes a part of kremlin, and this causes the NSS build to fail on ppc64le. The following patch let me build NSS successfully. I dont know what Kremlin is, what it does, or how to test it; but being a GCC platform it should be correct.

https://termbin.com/q42p

**Comment by msprotz** [comment]
@franziskuskiefer can I ask you for a sanity check on this one?

@clbr why the restriction on little-endian?

**Comment by clbr** [comment]
The code appeared to only be valid on LE, the other arches enabled were LE only. That, and I only have a LE machine.

**Comment by clbr** [comment]
Oh, you can remove the #include "prcpucfg.h", that's an NSS thing (I used a NSS endian macro at first, but __LITTLE_ENDIAN__ is a GCC one).

**Comment by franziskuskiefer** [comment]
Looks good to me as long as ppc64le has uint128 support :smile: 
I opened #167 with the patch.

**Comment by franziskuskiefer** [comment]
Fixed by #167. Please re-open if it makes any issues. Note that this will need to find its way to NSS before you'll see the NSS build working again.

**Comment by glandium** [comment]
NSS is similarly broken on ppc64 (big-endian), mips64el, s390x, ia64, riscv64, and sparc64.

**Comment by beurdouche** [comment]
@glandium Do we have a CI somewhere that shows us that ?

**Comment by glandium** [comment]
https://buildd.debian.org/status/package.php?p=nss

**Comment by beurdouche** [comment]
Thank you ! I’ll try to have a look at it.
