### ISSUE TITLE
Wierd size calculation in generated output

### ISSUE THREAD

**Issue by sander-visser** [FStarLang/kremlin#179]
See: https://github.com/ARMmbed/mbedtls/blob/mbedtls-2.22.0/3rdparty/everest/library/Hacl_Curve25519.c#L412

**Comment by msprotz** [comment]
Thanks for the issue. I get a 404 -- can you grant me access to the repo?

Thanks,

Jonathan

**Comment by sander-visser** [comment]
> 
> 
> Thanks for the issue. I get a 404 -- can you grant me access to the repo?
> 
> Thanks,
> 
> Jonathan

Fixed URL typo - sorry

**Comment by sander-visser** [comment]
Shouldn't this oneliner do?

memcpy(output, input, 10 * sizeof(uint64));

**Comment by msprotz** [comment]
Thanks, I agree that it's inelegant and I should fix this. However, this code seems fairly outdated (from several years back) and the newer version of this code does not feature such oddities. Could it be that the cheapest fix is to just submit a pull request to ARM to take the latest version of the code coming from upstream?

I have made sure that the code is available in GCC-compilable form (see https://github.com/project-everest/hacl-star/blob/master/dist/gcc-compatible/Hacl_Curve25519_51.c) or in C89 form if this is still a strict requirement in mbed (https://github.com/project-everest/hacl-star/blob/master/dist/c89-compatible/Hacl_Curve25519_51.c). Also, the new code has no more build headaches and it should suffice to take the dist/kremlin directory, along with the few headers that are mentioned here: https://github.com/project-everest/hacl-star/blob/master/dist/c89-compatible/Hacl_Ed25519.h#L34 (I even suspect that the first two #includes are superfluous).

Let me know if you'd like to give this a try.

Cheers,

Jonathan

**Comment by msprotz** [comment]
The underlying issue has been fixed via 8307c5ebc49bb072ad92ac45a25440d5066df72e
