### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jlamma** [FStarLang/kremlin#196]
Hey,
I'm having some trouble running `make` and can't seem to find a solution.
It eventually outputs the following error message: 
(though I do end up with a `./krml`...)
```
ocamlbuild -I src -I lib -I parser -I kremlib -use-menhir -use-ocamlfind -classic-display -menhir "menhir --infer --explain" Kremlin.native
ln -sf Kremlin.native krml
make -C kremlib
make[1]: Entering directory '/home/jlamma/fstar/kremlin/kremlib'
/home/jlamma/fstar/FStar/bin/fstar.exe --record_hints --use_hints --use_two_phase_tc true --odir .extract --warn_error @332 --cache_checked_modules --cache_dir obj --hint_dir hints --include ../runtime --cmi --already_cached 'Prims FStar -FStar.Kremlin.Endianness LowStar -LowStar.Lib'  --dep full C.Endianness.fst C.Failure.fst C.fst C.Loops.fst C.String.fst FStar.Kremlin.Endianness.fst LowStar.Lib.AssocList.fst LowStar.Lib.LinkedList2.fst LowStar.Lib.LinkedList.fst Spec.Loops.fst C.String.fsti LowStar.Lib.AssocList.fsti TestLib.fsti ../runtime/WasmSupport.fst FStar.UInt128.fst FStar.Date.fsti FStar.HyperStack.IO.fst FStar.IO.fst FStar.Int.Cast.Full.fst FStar.Bytes.fsti FStar.Dyn.fsti LowStar.Printf.fst LowStar.Endianness.fst > .depend
(Error 317) Expected FStar.Reflection.Types to be already checked but could not find it
1 error was reported (see above)
make[1]: *** [Makefile:58: .depend] Error 1
make[1]: Leaving directory '/home/jlamma/fstar/kremlin/kremlib'
make: *** [Makefile:28: kremlib] Error 2
```

I saw there were some issues with newer versions of OCaml, but this happened even with 4.06.0.

**Comment by msprotz** [comment]
kremlin assumes that you've run a full build of F* before in $FSTAR_HOME ... can you run `make` from F*'s toplevel directory?

**Comment by jlamma** [comment]
Thank you so much, that fixed it!
I had only run the following commands from F*'s `INSTALL.md`:
```
make 1 -j6
make libs -j6
```

**Comment by msprotz** [comment]
is INSTALL.md out of date? maybe you can submit a PR there to fix it? pinging @mtzguido who talked about "make libs" just this morning

**Comment by mtzguido** [comment]
Ah, indeed `INSTALL.md` is wrong: `make libs` only builds the binary objects for fstarlib/fstartaclib, it doesn't verify the library nor generate its `.checked` files, which Kremlin requires. Thanks for the heads up!
