### ISSUE TITLE
What should I do to update the kremlin?

### ISSUE THREAD

**Issue by zhaomengshan666** [FStarLang/kremlin#222]
I use `opam install kremlin`  to install the kremlin and succeed finally, but when I extract the `.fsti` to `.c`, there seems to be a problem about the version, the kremlin which I have installed is v0.9.6.0.
![image](https://user-images.githubusercontent.com/48112648/150629798-1f32fa22-3d58-40cb-abff-16e54109d81d.png)
Is there any way to solve this problem? Thanks.

**Comment by msprotz** [comment]
@R1kM is about to push an update to opam which should solve your problem

**Comment by R1kM** [comment]
Opam now has the latest version of KreMLin, added in https://github.com/ocaml/opam-repository/pull/20489 .
I'm closing this issue, please feel free to reopen if you encounter issues with the package.
