### ISSUE TITLE
EReturn of EUnit generates C "return UINT8_C(0);"

### ISSUE THREAD

**Issue by BarryBo** [FStarLang/kremlin#3]
AstToCStar.ml's translate_expr translates EUnit as:

  | EUnit ->
      CStar.Constant (K.UInt8, "0")

But this is incorrect when the enclosing method's return type is TUnit.  This repros in Spartan SHA256UpdateWhenNoUnprocessedBytes.

**Comment by msprotz** [comment]
This should be fixed by b3df85e
