### ISSUE TITLE
Substitute attribute with push_frame(); pop_frame() does not work

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/kremlin#35]
Using the "substitute" attribute on a function that pushes and pops frames makes kremlin fail with `[AstToCStar.mk_expr]: should not be here (pop_frame)`.
Can we not just have in inlined into a new block ?

**Comment by msprotz** [comment]
```
module Substitute

open FStar
open FStar.ST

[@ "substitute" ]
private let test (b: Buffer.buffer Int32.t): Stack unit
  (requires (fun h -> Buffer.live h b /\ Buffer.length b > 0))
  (ensures (fun _ _ _ -> true))
=
  push_frame ();
  Buffer.upd b 0ul 0l;
  pop_frame ()

val main: Int32.t -> FStar.Buffer.buffer (FStar.Buffer.buffer C.char) ->
  ST.Stack Int32.t (fun _ -> true) (fun _ _ _ -> true)
let main argc argv =
  push_frame ();
  let b = Buffer.create 1l 1ul in
  test b;
  pop_frame ();
  C.exit_success
```

The example above works for me. Can you modify it so that it fails?

**Comment by msprotz** [comment]
Closing... no repro.

**Comment by beurdouche** [comment]
I think I have seen this at some point, but only if you forgot a `push_frame()`

**Comment by msprotz** [comment]
But can the code verify in the Stack effect if you forgot a push_frame?
