### ISSUE TITLE
Code dependency analysis

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/kremlin#36]
Circular dependencies are painful to handle, in particular when they come from types that may be used both in specs and in code.

@prosecco suggested that in the case where we bundle into an "api" file, we could just ask kremlin to bundle everything in it (code & specs), and remove whatever is dead-code in the file (which is pretty much all the specs).
Is that easy to achieve ?

**Comment by msprotz** [comment]
This is already what -bundle does. However, the order of operations is:
1. bundle, which possibly breaks the well-formed module topological order
2. dependency analysis to re-order the bundled modules in a topological order
3. drop unreachable code in a given file.

I think you're asking me to swap 2. and 3.

**Comment by prosecco** [comment]
I am a little bit confused. How come the poly1305/curve25519 targets in code/ work right now?
I am able to bundle and throw away specs. How come this doesn’t trigger the circular dependency?

-Karthik

**Comment by msprotz** [comment]
If you have a dependency graph as follows:

A <- B <- C

where B is spec-only, and you do -bundle Foo=A,C then you get a circular dependency

if the specs from B are never used in actual code reachable via the API Foo, then dropping unreachable code then doing the dependency analysis will avoid the loop.

This *may* be the situation that JK is in.

**Comment by jkzinzindohoue** [comment]
Well when I put everything in a single module `A` which has an api `val a: ...` which I expect to be the only non-static function in the extracted file, I still see some functions that come from specifications, were bundled in the file and are now called anywhere.
I will file an example.

**Comment by msprotz** [comment]
File another bug?
