### ISSUE TITLE
Size limitation on length of `createL` litterals

### ISSUE THREAD

**Issue by jkzinzindohoue** [FStarLang/kremlin#42]
Is there a specific reason for the limitation on the input list size at https://github.com/FStarLang/kremlin/blob/master/src/CStarToC.ml#L205 ?

In particular, not respecting this constraint leads to a fatal error:
```
Fatal exception raised in Test_test
Fatal error: exception File "src/Constant.ml", line 50, characters 2-8: Assertion failed
```

The reason I am asking is that I have test vectors that are larger than that (~1024 bytes).

**Comment by msprotz** [comment]
Absolutely not... please feel free to change this to uint32_of_int!
