### ISSUE TITLE
Support pointer of the same struct type in struct definition

### ISSUE THREAD

**Issue by photoszzt** [FStarLang/kremlin#44]
Currently, there's no way to define a type that would translate to the following C struct definition: 
typedef struct  {
    int32_t x01;
    struct t* x10;
}
t;

I have tried to use
type t = 
       | T: Int32.t -> Buffer.buffer t -> t

But what this translates to is

typedef struct {
     int32_t x01;
     t* x10;
}
t;
which does not work for C.

**Comment by msprotz** [comment]
0b2f9a9d7f5ffb4287b319bd1d520e3243f6cc18

Thanks for the bug report!

PS: this change introduced another bug which shall be fixed shortly, so this is a little bit broken right now
