### ISSUE TITLE
List of C undefined behavior that we're not protecting against

### ISSUE THREAD

**Issue by msprotz** [FStarLang/kremlin#48]
- [x] Shifts by the width of the integer type (e.g. shift by 64 for a uint64_t), witnessed by `krml-test-hacl.exe` with `clang -fsanitize=undefined,address`
  - [x] Immediate fix: rewrite the code to avoid undefined behavior
  - [ ] Mid-term fix: make them abstract to stop the bitvector-based model from leaking its overly precise specification; will break at least three places in HACL* (see mitls/hacl-star#22)
  - [x] Long-term fix: make `s < 64` a pre-condition rather than `s < 64 ==>` a post-condition (sent email to Nuno); possibly fix all the "underspec" variants to behave that way, too (e.g. `add_underspec`). This is a lot of work.
- [x] Unaligned memory writes. Currently, our Buffer interface conveniently enforces this because `sub` takes an index, not a number of bytes. We don't allow casts from an arbitrary buffer to a `char *`, so userland code has no way to perform un-aligned memory accesses. Some hand-written C functions break that invariant, though; `store_128_le`, for instance, has undefined behavior. Reading https://pzemtsov.github.io/2016/11/06/bug-story-alignment-on-x86.html at Andreas' suggestion, `memcpy` seems like the way to go to implement these few functions without undefined behavior.
- [x] Zero-sized arrays (`Buffer.create` should have a proper precondition). This really ought to be fixed.
- [x] `Buffer.sub` is a total function which means one can always generate `p + 42` even though `p` has been freed. I believe this is undefined ("If an object is referred to outside of its lifetime, the behavior is undefined.").

Will add more as I re-read John's blog post.

**Comment by andreas23** [comment]
John Regehr has a comprehensive list of UB in C, as well as some tools to identify them: https://blog.regehr.org/archives/1520

**Comment by msprotz** [comment]
Yes, I am an avid reader of John's blog and these are just whatever showed up when I ran krml-test-hacl.exe through ubsan.

**Comment by tchajed** [comment]
I don't think fixing the `_underspec` functions is all that much work, especially now when they're not used (across all of Everest, at least). Also note that these are already fine for unsigned integers, where overflow/underflow is defined by C; they're only problematic for signed integers.

Similarly, while making `shift_left` and `shift_right` abstract we might as well also move `U32.v s < n` into the precondition (and do this for all the integer types).

**Comment by tchajed** [comment]
I implemented the long-term fix for integer shifts above in https://github.com/FStarLang/FStar/commit/f73f295ed0661faec205fdf7b76bdd85a2a94a32. We'll have to see what the impact on mitls and HACL* are, but F*'s specs are now safe.

**Comment by msprotz** [comment]
The new LowStar.Buffer from @tahina-pro fixes the remaining bits (issues with sub and create), so for me, that's a long-standing issue that can be closed. Thanks to everyone involved.
