### ISSUE TITLE
`C.Loops.interruptible_for` is unimplemented

### ISSUE THREAD

**Issue by tchajed** [FStarLang/kremlin#49]
The F* implementation of `interruptible_for` has no corresponding syntax and printing to C.

**Comment by msprotz** [comment]
good catch; do you need it for your experiments?

**Comment by tchajed** [comment]
Yes, this seems to be the best way to implement early termination for validation.

**Comment by msprotz** [comment]
Implemented by 98c086d4ea92ce22a4296d2d828fd3b5db808b8f and 9f61f1bf979b4322607a5d93c82fe82c4733e986
