### ISSUE TITLE
Feature request:  support for externally-resolved function names

### ISSUE THREAD

**Issue by BarryBo** [FStarLang/kremlin#5]
For SHA256, the Dafny code implements all but two static methods , which are implemented in Spartan.  Those two methods have Dafny-side declarations but no definitions.

I would like to be able to emit something like a DFunction, except that it would have no expr for the body.  This could be a new DExternalFunction, or simply a DFunction with EUnit or EAny as a special-case expression.  The code-gen would be to emit a C declaration into the appropriate .h file, but not generate any definition code into a C file.

Alternatively, if Kremlin allowed an AST to request an additional #include preprocessor directive to be emitted into the top of the current .h file, I could hard-code the declaration in a checked-in header file.

**Comment by msprotz** [comment]
There the `-add-include` flag for that purpose. Would it solve your use-case? That's exactly what I'm doing for the tests.

**Comment by BarryBo** [comment]
Perfect – the -add-include switch does what I need. ☺
Barry

**Comment by msprotz** [comment]
I thought about it further and it's better to have something like `DExternal`, in the sense that Kremlin will want to know about the types of these external functions in order to perform rewritings. For instance:

foo(if true then bar () else baz ())

needs to be rewritten to

t tmp;
if true then
  tmp = bar ();
else
  tmp = baz ();
foo(tmp);

and for that you need to know the type of bar and baz to properly infer the type needed for tmp.

**Comment by BarryBo** [comment]
Agreed!  Or else just an existing DFunction that doesn’t specify a body.

**Comment by msprotz** [comment]
I'm wary of re-using DFunction because 1) you'd have to supply a non-empty body to make it comply with the checking rules, and 2) Kremlin wouldn't know that it isn't supposed to emit anything in the .c or the .h...

**Comment by msprotz** [comment]
Done in e841bec

**Comment by BarryBo** [comment]
| DExternal of (lident * typ)

I’m not sure how to express a method’s return type and argument types as a single typ.  If I just specify the return type here, Checker.ml complains “Not a function being applied” because there are zero arguments.

Should this really be (lident * typ list) ?

Barry

**Comment by msprotz** [comment]
Sorry, I should've mentioned that for functions using a `TArrow` works; i.e. `t f(t1 x1, ..., tn xn)` becomes `t1 -> ... -> tn -> t`

**Comment by msprotz** [comment]
Should've mentioned that this should be a TArrow type!


~ jonathan

________________________________

**Comment by BarryBo** [comment]
Agreed – you suggested that in a previous email thread.  Dafny has been generating TArrow successfully since then.
Barry
