### ISSUE TITLE
FStar.Buffer does not have a wrapper for C's memcmp

### ISSUE THREAD

**Issue by tchajed** [FStarLang/kremlin#50]
There are `blit` and `fill` for `memcpy` and `memset`, but no wrapper for `memcmp`.

One design choice is what type to give it. On the one hand `memcmp` should work for any `t` if it's only being used for equality comparisons, whereas for a `buffer U8.t` it can also promise to return positive/negative numbers appropriately. My preference would be to start with just equality comparisons for any type:

```
// corresponds to memcmp, but without the sign comparison
assume val compare: #t:Type -> b1:buffer t -> b2:buffer t ->
                    len:UInt32.t{v len <= length b1 /\ v len <= length b2} -> Stack Int32.t
 (requires (fun h0 -> live h0 b1 /\ live h0 b2))
 (ensures (fun h0 r h1 -> live h1 b1 /\
                       live h1 b2 /\
                       modifies_none h0 h1 /\
                       (Int32.v r == 0 <==>
                        Seq.slice (as_seq h1 b1) 0 (v len) ==
                        Seq.slice (as_seq h1 b2) 0 (v len))))
```

which extracts to something like `memcmp(b1, b2, len*sizeof(t))`.

**Comment by msprotz** [comment]
https://github.com/FStarLang/kremlin/blob/master/kremlib/kremlib.h#L41 ?

**Comment by msprotz** [comment]
I think you could add it and use the same trick in kremlib.h as above for the implementation of it, provided that the signature of Buffer.eqb is not what you want. Or, perhaps fix Buffer.eqb to give you a strong post-condition?

**Comment by msprotz** [comment]
Seems like `eqb` is going to foot the bill... closing.
