### ISSUE TITLE
Extraction reports type mismatches due to type aliases for function types

### ISSUE THREAD

**Issue by tchajed** [FStarLang/kremlin#51]
`f` doesn't extract to C in the following example due to a type mismatch between `bool` and `bool_function () == bool -> bool`. I'm not sure where that comes from, but adding `unfold` to the alias `bool_function` fixes the issue, at the cost of affecting verification.

```
module Type_alias

open FStar.HyperStack
open FStar.HyperStack.ST

(* this unfold is required to get f to extract correctly, but is undesirable
from a verification perspective *)
// unfold
let bool_function (spec: nat -> nat) = bool -> St bool

let f (y:bool) : bool_function (fun x -> x) =
  fun x -> x && y
```

**Comment by jkzinzindohoue** [comment]
As far as I know, Low* does not support higher order and partial application, so I would not expect this to extract to C.

**Comment by tchajed** [comment]
Well after unfolding `bool_function` it's clear that `f` can be extracted to a two-argument function, which is exactly what happens with `unfold`.

We've discussed an example like this in the context of my key-value store parsing experiments and decided that `inline_for_extraction` on `bool_function` (which currently can't really have any impact) should have the behavior `unfold` currently does, except that it would only apply to extraction and not verification.

**Comment by msprotz** [comment]
What happens is probably along the lines of: the definitions of the `bool_function` type, for some reason or another (most likely the fact that it mentions `nat`) is not expressible in Low*. The net result is, applications of `bool_function` to its erased argument `unit` remain, but the missing definition of `bool_function` prevents these applications from expanding into `bool -> bool`, hence the error message.

`inline_for_extraction` on the type definition is indeed the right way to solve this.

If you want to improve the error message, or possibly write some of the things you're learning in MANUAL.md, then by all means feel free to edit...

Thanks,

Jonathan
