### ISSUE TITLE
Wrappers around loops are not extracted with [@"substitute"]

### ISSUE THREAD

**Issue by tchajed** [FStarLang/kremlin#55]
The following doesn't extract. What I want is to inline `for'` and then have the special handling of `C.Loops`, without having to mark the wrapper as `unfold` (since its purpose is to ease verification).

```fstar
module Extract_for_wrapper

open C.Loops
open FStar.HyperStack.ST

// unfold does work, but is undesirable for verification
[@"substitute"]
let for' = for

let for'_noop (n:UInt32.t) : Stack UInt32.t
  (requires (fun h0 -> True))
  (ensures (fun h0 r h1 -> r == n)) =
  let _ = for' 0ul n (fun h i -> True) (fun i -> ()) in
  n
```

To compile this, use `krml -skip-compilation extract_for_wrapper.fst`. Note that it requires `$KREMLIN_HOME/kremlib` on the include path to verify with F*.

**Comment by jroesch** [comment]
`inline_for_extraction` now produces the correct code for this:

```
λ ferrous kremlin → λ git master* → cat Extract.c
#include "Extract.h"

uint32_t Extract_for__noop(uint32_t n1)
{
  for (uint32_t i = (uint32_t )0; i < n1; i = i + (uint32_t )1)
  {

  }
  return n1;
}
```

cc @protz
