### ISSUE TITLE
How to pass a DTypeFlat to a function byref?

### ISSUE THREAD

**Issue by BarryBo** [FStarLang/kremlin#6]
I am encoding a DTypeFlat argument as:

       {
        "name": "this",
        "typ":["TQualified",[["DafnyDefaultModule"],"SHA256Context"]],
        "mut": false
       }

but this generates a byval copy... in C, "DafnyDefaultModule_SHA256Context this", without a '*".

What is the correct encoding for a byref struct?  These are mutable by the callee.

**Comment by msprotz** [comment]
Would an array of size one work?

**Comment by BarryBo** [comment]
Yes, I think that would work nicely.

**Comment by BarryBo** [comment]
Sorry, an array of size 1 doesn't work.  To modify a field inside the EFlat, I would have to copy it out of the EBuffer into a temp variable using EBufRead, then modify the field, then write back with EBufWrite.  That feels very awkward and slow.

**Comment by msprotz** [comment]
Would an EAssign work? You *should* be able to put on the left-hand side of an EAssign an array index operation followed by a field access operation.


~ jonathan

________________________________

**Comment by BarryBo** [comment]
Yes, it is working...   EAssign (  EField (EBufRead var, 0) fieldname), right-hand-side-expr).

**Comment by msprotz** [comment]
Excellent news. I should probably get rid of the redundancy between EBufWrite and EAssign now, but I'll leave that to later.
