### ISSUE TITLE
Support ArrayStruct (aka FStar.Pointer)

### ISSUE THREAD

**Issue by tahina-pro** [FStarLang/kremlin#60]
Feature request: we should be able to extract Low* code that uses ArrayStruct (aka FStar.Pointer) instead of legacy buffers (aka FStar.Buffer). Indeed, ArrayStruct supports a much wider range of C features such as:
* arrays
* structs
* nested arrays and structs
* pointers and multiple-indirection pointers
* uninitialized data
and redefines a notion of buffers on top of pointers to arrays to provide users with pointer arithmetic for subarrays.

Several issues though:
* Can this extraction coexist with legacy buffers?
* Contrary to legacy buffers, ArrayStruct can only represent types coded in a fixed grammar (FStar.Pointer.Base.typ). In other words, types become deeply embedded, whereas operations remain shallow. This might come at odds with other feature requests such as #58 if references to arbitrary F* types are actually needed.
* It could be useful to harmonize the grammar of C types supported by ArrayStruct with KreMLin's.

**Comment by fournet** [comment]
For miTLS we need hacl-star, FStar.Pointer, and Hyperstack's refs and mrefs to gracefully coexist. At the same time we are concerned about mixed modifies clauses and framing.
