### ISSUE TITLE
Next steps for F*-KreMLin extraction & interaction

### ISSUE THREAD

**Issue by msprotz** [FStarLang/kremlin#64]
- [x] Support for mutually recursive datatypes (cleaning up and merging Jared's work)
   - jonathan to start on this
- [x] support for machine integer literals in patterns
- [x] Vector, rawbytes, and bytes, implemented both in F* and in kremlib
   - nik to start on the F* side
- [x] References as size 1 buffers (for hyperstack refs, to be merged from the branch)
   - jonathan to start on this
- [ ] Attributes per binding and not per block of mutually recursive type definitions
   - allowed in the ML AST, but still per sigelt in the F* parse tree and internal AST
- [x] Forward StackInline to KreMLin
- [x] Deprecate `[@"substitute"]`
   - jonathan to start on this -- actually can't do it because kremlin knows (syntactically) that some expressions are read-only and do not need to be hoisted, i.e. for `f b.(0) b.(1)` F\* will introduce intermediary variables while kremlin will not -- hence the need for a `Read` effect
- [x] Implement `[@ (const x) ]` (and possibly other SAL-like annotations https://msdn.microsoft.com/en-us/library/hh916382.aspx)
  - Change the syntax of attributes to be more flexible than just atomic term
- [ ] Forward location information to KreMLin
- [x] Forward names for parameters of assumed vals (from Jared's branch)
- [x] Investigate a `Read` effect so that we can truly deprecate substitute

- [ ] push/pop_frame are a bit brittle. Can we do better with with_frame? Unclear.

CC @nikswamy

**Comment by nikswamy** [comment]
cc @jroesch

**Comment by nikswamy** [comment]
cc @jroesch

**Comment by msprotz** [comment]
Note: KreMLin now recovers from intermediary variables by using a syntactic criterion, meaning that [@"substitute"] can be truly deprecated and the Read effect can be put on the back burner.

**Comment by msprotz** [comment]
Closing... attributes per binding don't seem to be needed, and with_frame seems more complicated than it's worth.
