### ISSUE TITLE
Kremlib.h separation in different files for easier integrations in other projects

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/kremlin#69]
As discussed before, we typically don't want everything that is currently in `kremlib.h` for production.
We have an example of split in 2 parts for HACL*  based on the current `kremlin/kremlib.h`
https://github.com/mitls/hacl-star/tree/master/snapshots/kremlib

Deciding of a nicer splitting is not urgent but is important so that we can remove unused code from production code such as the one used in NSS, while having HACL* `kremlib(s).h` aligned on Kremlin.

**Comment by msprotz** [comment]
currently underway in https://github.com/FStarLang/kremlin/tree/cleanup-kremlib/kremlib, including a restructuring of the kremlib/ directory -- the goal is to have kremlin automatically pick up the right -add-include foo.h and foo.c arguments for you, unless using `-minimal`

**Comment by msprotz** [comment]
Merged in a21b1e0bad4b1bc80cc520fbeb01bc385fef5641 and others
