### ISSUE TITLE
Types with multiple constructors not supported

### ISSUE THREAD

**Issue by BarryBo** [FStarLang/kremlin#7]
In F*:
```
type clientState = 
  | C_Idle
  | C_HelloSent
```
The F* compiler fails with:
Warning: not translating definition for clientState (and possibly others)
Warning: not translating definition for main (Failure("todo: translate_expr [MLE_CTor]"))

The Dafny equivalent is used by AES:
`datatype Algorithm = AES_128 | AES_192 | AES_256`
and I don't see how to encode this in the current Kremlin JSON.

Dafny emits a fairly complex piece of C# code - an abstract class called `Base_Algorithm` with no members, then separate `Algorithm_AES_128`/`Algorithm_AES_192`/`Algorithm_AES_256` classes derived from `Base_Algorithm`, with appropriate constructors.  Then it generates a public struct `@Algorithm` with a single member variable, `_d`, of type `Base_Algorithm`.  This struct's constructor creates an `Algorithm_AES_128` instance in its default constructor, to give `_d` a value.  And it generates helper methods, `is_AES_128`/`is_AES_192`/`is_AES_256`, to help with dynamic typing elsewhere in the language.

**Comment by msprotz** [comment]
Yes, this is the next item on my priority list. Will be implemented using a tagged union, and an enum for the various cases.

**Comment by msprotz** [comment]
This specific case should now be supported with an enum and a switch (see `test/DataTypesSimple.fst`). The general case shall be supported soon.

**Comment by BarryBo** [comment]
Success – the codegen from this Dafny code:
datatype Algorithm = AES_128 | AES_192 | AES_256

Becomes this C code:
typedef enum {
  AESModule_Algorithm_AES_128,
  AESModule_Algorithm_AES_192,
  AESModule_Algorithm_AES_256
}
AESModule_Algorithm;


Dafny’s .NET code-gen is considerably more complex, as it generates separate C# classes for each constructor, along with its own runtime type check functions and a common base class.

Barry

**Comment by msprotz** [comment]
This is finally complete -- see https://github.com/FStarLang/kremlin/blob/master/test/DataTypes.fst for an example.

There are probably bugs lurking. @BarryBo how much pattern-matching from Dafny do you intend to compile to Kremlin? In particular, does Dafny have nested or-patterns? (e.g. `match e with Foo (A | B) -> ...`).

**Comment by BarryBo** [comment]
Currently, none.  We needed the type defined, essentially just this:
```
type t =

  | A

  | B
```
and it is never used from Dafny code we are compiling.  The calling application will pass 'A' or 'B' values directly to the Spartan code, which does its own matching.

Dafny does not have complex pattern matching like F*.  It essentially generates a C# if/elseif/.../endif statement using its own helper routines for matching types.
