### ISSUE TITLE
Reduce creation of new C variables via some use analysis

### ISSUE THREAD

**Issue by BarryBo** [FStarLang/kremlin#73]
I have idiomatic code like this, where 'p' is being used as the offset to append to inside a buffer of bytes.

`  let p = append8 packet 0ul 0x63uy in`
`  let p = append64 packet p csm.connectionID in`
`  let p =  append32 packet p (Cast.uint64_to_uint32 csm.packetNumber) in`

The C extraction declares p, p1, and p2, matching precisely the F* variable scoping.

I would like to see Kremlin recognize that the first p is used exclusively before the second p is defined, and has the same type.  In that case, the declaration of p1 can be omitted, by assigning back into the original variable p.

`  uint32_t p = Utils_append8(packet, (uint32_t)0U, (uint8_t)0x63U);`
`  uint32_t p1 = Utils_append64(packet, p, csm.connectionID);`
`  uint32_t p2 = Utils_append32(packet, p1, (uint32_t)csm.packetNumber);`
would become
`  uint32_t p = Utils_append8(packet, (uint32_t)0U, (uint8_t)0x63U);`
`  p = Utils_append64(packet, p, csm.connectionID);`
`  p = Utils_append32(packet, p, (uint32_t)csm.packetNumber);`

**Comment by msprotz** [comment]
I forgot to comment on this one but it's not trivial to do, because by the time KreMLin receives the program, the names have already been numbered by F*, so I'd have to change F* to either have a proper notion of scope, or transmit DeBruijn directly to KreMLin.

**Comment by msprotz** [comment]
Finally implemented via `-fmerge=prefix`
