### ISSUE TITLE
Improve code-gen for pointer dereferences

### ISSUE THREAD

**Issue by BarryBo** [FStarLang/kremlin#74]
This code:
`inc_packetNumber (!*cs).csm_state;`
extracts to:
`  Types_connection uu____3492 = *cs;`
`  Types_connection_mutable *uu____3489 = uu____3492.csm_state;`
`  Mutators_inc_packetNumber(uu____3489);`

I'm not sure where the temporaries are coming from, but the code could be compacted down to:
` Mutators_inc_packetNumber(cs->csm_state);`

**Comment by msprotz** [comment]
This should now all be fixed.
