### ISSUE TITLE
When KreMLin is driving F*, certain type-errors compile without warning

### ISSUE THREAD

**Issue by pierrebeaucamp** [FStarLang/kremlin#86]
I have the following snippet of code:

```fs
module Main

val foo: bool -> Type0
let foo b = if b then nat else nat

val bar: b:bool -> foo b
let bar b = "hello"
```

If I simply call `fstar.exe main.fst`, it throws the correct error:
```
./main.fst(7,18-7,19): (Error) Subtyping check failed; expected type Main.foo b; got type Prims.string (see also ./main.fst(0,0-0,0))
Verified module: Main (333 milliseconds)
1 error was reported (see above)
```

However, if I call `krml -skip-linking main.fst`, the command succeeds just fine. 

---

What is even stranger, if I change my `foo` function to the following, kremlin will indeed throw an error as well:
```fs
val foo: bool -> Type0
let foo b = nat
```
```
./main.fst(7,18-7,19): (Error) Expected expression of type "Main.foo b"; got expression ""hello"" of type "Prims.string"
1 error was reported (see above)
```

It seems to me as if it fails once the code has branches?

---

F* 0.9.5.0
platform=Linux_x86_64
compiler=OCaml 4.04.2
date=2018-04-09T01:40:48+00:00

F-Star commit: `a3462014fea5296e2f1baeee1cb1838160010bba`
KreMLin commit: `c2b3979fe3985d0cff32ae550a4f515839ecef46`

**Comment by msprotz** [comment]
Hello,

Sorry for the long delay, I was on vacation. Right now, indexed types are not supported by Low*, as they would have to be extracted to anonymous unions in C, and this is something that we do not have theory for.

There have been various requests for it in the past, and I may start to prototype something soon, but in the meanwhile the current advice is to switch to tagged unions (i.e. `type foo = | Bar: nat -> foo | Baz: nat -> foo` along with a boolean, e.g. `fun (f: foo) (x:b{ if b then Bar.? foo else Baz.? foo }) -> ...`

I hope to write about the status of this soon in the upcoming Low*/KreMLin tutorial.

Thanks,

Jonathan
