### ISSUE TITLE
Code stability request - more stable names for uu__*_* temp variables

### ISSUE THREAD

**Issue by BarryBo** [FStarLang/kremlin#88]
Between two Everest drops, the name of a uu__ variable changed.  I'm not sure what the seed is for this, but the variable is an argument to a function, and so it can/should be named with something that is scoped to the function, and stable from drop to drop.

Besides the comment header at the top of TLSInfo.c, this is the first change, down on line 500.
`bool TLSInfo_honestMS(TLSInfo_msId uu___76_1731)`
became
`bool TLSInfo_honestMS(TLSInfo_msId uu___76_1720)`

This creates a diff that has to be code-reviewed when we drop extracted C code into external projects.

**Comment by msprotz** [comment]
This should be relatively easy to do, and a good suggestion.
