### ISSUE TITLE
Can't get StringLit example to compile

### ISSUE THREAD

**Issue by pierrebeaucamp** [FStarLang/kremlin#97]
Sorry for yet another "beginner" question, but I think there is the possibility that this is a genuine bug, so I decided to open an issue instead of posting on the F* mailing list.

In short, I'm not able to run the `StringLit.fst` example in the test directory. The reason for this seems to be that the generated C code doesn't include all the necessary headers.

A straight forward invocation of `krml StringLit.fst` fails with the following messages:

```
⚡ Generating object files
✔ [CC,./Prims.c] (use -verbose to see the output)
✘ [CC,./FStar.c] (use -verbose to see the output)
In file included from ./FStar.c:8:0:
./FStar.h:15:8: error: unknown type name ‘Prims_string’
 extern Prims_string FStar_String_strcat(Prims_string x0, Prims_string x1);
        ^~~~~~~~~~~~
./FStar.h:15:41: error: unknown type name ‘Prims_string’; did you mean ‘Prims_prop’?
 extern Prims_string FStar_String_strcat(Prims_string x0, Prims_string x1);
                                         ^~~~~~~~~~~~
                                         Prims_prop
./FStar.h:15:58: error: unknown type name ‘Prims_string’; did you mean ‘Prims_prop’?
 extern Prims_string FStar_String_strcat(Prims_string x0, Prims_string x1);
                                                          ^~~~~~~~~~~~
                                                          Prims_prop
./FStar.h:17:46: error: unknown type name ‘Prims_string’; did you mean ‘Prims_prop’?
 extern void FStar_HyperStack_IO_print_string(Prims_string x0);
                                              ^~~~~~~~~~~~
                                              Prims_prop
cc1: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
cc1: all warnings being treated as errors

Warning 3: run_or_warn: the following command failed:
gcc -I /nix/store/q44mcdcgn31z3y9nkn2v6f4ip52cya2z-kremlin/include/ -I /nix/store/q44mcdcgn31z3y9nkn2v6f4ip52cya2z-kremlin/lib/kremlin -I . -Wall -Werror -Wno-unused-variable -Wno-unknown-warning-option -Wno-unused-but-set-variable -g -fwrapv -fstack-check -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wno-parentheses -std=c11 -c ./FStar.c -o ./FStar.o
Warning 3 is fatal, exiting.
```

at that point, `Prims.h` looks like this:

```
/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: krml -fsopt=--cache_off StringLit.fst
 * F* version: <unknown>
 * KreMLin version: <unknown>
 */

#include "kremlib.h"
#ifndef __Prims_H
#define __Prims_H




typedef void *Prims_prop;

#define __Prims_H_DEFINED
#endif
```

Based on the error message, I tried adding some include statements manually. This gets me further into the compilation:

`krml -add-include=\"kremlin/prims_string.h\" -add-include=\"kremlin/c_string.h\" StringLit.fst`

```
⚡ Generating object files
✔ [CC,./Prims.c] (use -verbose to see the output)
✔ [CC,./FStar.c] (use -verbose to see the output)
✔ [CC,./StringLit.c] (use -verbose to see the output)
✔ [CC,./LowStar.c] (use -verbose to see the output)
✔ [CC,./C_Loops_Spec_Loops.c] (use -verbose to see the output)
✔ [CC,/nix/store/q44mcdcgn31z3y9nkn2v6f4ip52cya2z-kremlin/lib/kremlin/kremlib.c] (use -verbose to see the output)
✘ [LD] (use -verbose to see the output)
/nix/store/2kcrj1ksd2a14bm5sky182fv2xwfhfap-glibc-2.26-131/lib/crt1.o: In function `_start':
/build/glibc-2.26/csu/../sysdeps/x86_64/start.S:110: undefined reference to `main'
./StringLit.o: In function `StringLit_main':
/home/pierrebeaucamp/Code/temp/kremlin-tests/./StringLit.c:23: undefined reference to `FStar_HyperStack_IO_print_string'
/home/pierrebeaucamp/Code/temp/kremlin-tests/./StringLit.c:24: undefined reference to `FStar_HyperStack_IO_print_string'
/home/pierrebeaucamp/Code/temp/kremlin-tests/./StringLit.c:25: undefined reference to `FStar_HyperStack_IO_print_string'
/home/pierrebeaucamp/Code/temp/kremlin-tests/./StringLit.c:26: undefined reference to `FStar_HyperStack_IO_print_string'
./StringLit.o: In function `StringLit_test':
/home/pierrebeaucamp/Code/temp/kremlin-tests/./StringLit.c:12: undefined reference to `FStar_String_strcat'
./StringLit.o: In function `StringLit_cat':
/home/pierrebeaucamp/Code/temp/kremlin-tests/./StringLit.c:17: undefined reference to `FStar_String_strcat'
collect2: error: ld returned 1 exit status

Warning 3: run_or_warn: the following command failed:
gcc -I /nix/store/q44mcdcgn31z3y9nkn2v6f4ip52cya2z-kremlin/include/ -I /nix/store/q44mcdcgn31z3y9nkn2v6f4ip52cya2z-kremlin/lib/kremlin -I . -Wall -Werror -Wno-unused-variable -Wno-unknown-warning-option -Wno-unused-but-set-variable -g -fwrapv -fstack-check -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wno-parentheses -std=c11 ./Prims.o ./FStar.o ./StringLit.o ./LowStar.o ./C_Loops_Spec_Loops.o ./kremlib.o
Warning 3 is fatal, exiting.
```

I didn't try to resolve that particular error message yet, but my next step would be to invoke each step of kremlin manually to add additional include paths to gcc or similar. However, I'm surprised that I even have to add so many manual includes in the first place.

To me, this seems like a bug. If it is not and I'm just missing something obvious, I apologize for opening an issue.

Fyi, both F* and Kremlin are build from master (might be a couple of days old though at this point). F-Star was build using the ocaml snapshot.

PS: Just in case this makes any difference, I'm also passing `-fsopt="--cache_off"` to krml, but I don't see how this affects my problem

**Comment by msprotz** [comment]
It's a totally valid question. You need to pass to kremlin the kremstr.c file from the kremlib/ directory.

Generally, the Makefile in the test directory tells you which flags you need for a particular example: see https://github.com/FStarLang/kremlin/blob/master/test/Makefile#L92 in your case

This is in the process of being overhauled, so that things get easier. The plan is to pre-compile kremlin and generate libkremlin.a, so that one can pass it at link-time and let the linker drop all unused symbols. KreMLin would conceivably take care of finding libkremlin.a and passing it unconditionally at the final link-time.

StringLit mixes GC-backed strings (Prims.string) and C-like strings (C.String.t) so that's why you need to -add-include '"kremlin/prims_string.h"'. Generally, there is a strong desire to minimize the set of includes in the generated source files, so that the code can be easily distributed, but it's worth debating whether kremlib.h should include everything under the sun, leaving it up to advanced users to use `-minimal` and `-add-early-include` instead.
