### ISSUE TITLE
Overflow bugs

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/kremlin#99]
`FStar.UInt.max_int` is defined as `pow2 n - 1`, which after kremlin looks like

```
Prims_op_Subtraction(Prims_pow2(n), (krml_checked_int_t)1);
```

Those, `Prims_pow2(n)` needs to be able to compute `2^32`, but that doesn't fit into an `int32_t`, thus `RETURN_OR` will fail the integer overflow check. I'm not sure the defining `Prims_int` as an `int32_t` is fine here; at least we would need an unsigned version of it, e.g. for `(UInt.fits … 32)` checks.

**Comment by wintersteiger** [comment]
Forgot to add: `make test` in `mitls-fstar/src/tls` triggers this problem:

```
…
Prims.{int,nat,pos} integer overflow at kreminc/kremlin/prims_int.h:48
Makefile:109: recipe for target 'test' failed
make[1]: *** [test] Error 252
```

**Comment by msprotz** [comment]
`Prims.int` is an arbitrary large integer number, that is never representable by any of the `{u,}int_*` types no matter what. The only valid implementation strategy that preserves the F* semantics for this type is to use automatically-managed generic bignums, e.g. GMP with refcounting.

As such, `Prims.{int,nat,pos}` are not Low* and are not compilable by KreMLin by default. As a helper to facilitate the transition of code from F\* to Low\*, KreMLin provides, as an opt-in header (`-add-include '"kremlin/prims_int.h"'`), a correct but incomplete implementation of these types using bounded integers along with run-time checks. Defining `krml_checked_int_t` to be a larger type would i) complicate overflow checks and ii) only push the problem further down the line. The solution is to rewrite the original code to no longer rely on intermediary computations of type `Prims.{int,nat,pos}` and directly operate on machine integers instead.

Thanks,

Jonathan

**Comment by wintersteiger** [comment]
Yes, that's pretty much what I concluded too. It would have saved me a bunch of time if kremlin hat simply reported "This is not Low*" instead of throwing a runtime error long afterwards...

**Comment by msprotz** [comment]
This is a long-standing feature request to better report these kinds of issues; however, there are probably hundreds if not thousands of such cases all over the miTLS source code, so right now the warning would probably have to be disabled anyhow.
